name: modern_ttrpg
description: Modern version of tabletop RPG game.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.15.0
  firebase_crashlytics: ^2.8.1
  flutter:
    sdk: flutter
  games_services: ^2.0.7
  go_router: ^3.0.1
  google_mobile_ads: ^1.1.0
  in_app_purchase: ^3.0.1
  just_audio: ^0.9.28
  logging: ^1.0.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test: ^1.19.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
